api_url: "http://localhost:8080/api"
user_token: ""

app:
  port: "3000"
  name: "Quan ly may in"

test:
  ip: "192.168.1.228"
  user: "admin"
  password: "admin"
  post_server: false

ws:
  url: ""  # example: ws://main-server:9000/ws/agent
  token: ""
  auto_connect: false
