api_url: "http://localhost:8080/api"
user_token: ""
database_url: "sqlite:///storage/data/agent_config.db"

app:
  port: "3000"
  name: "Quan ly may in"

test:
  ip: "192.168.1.228"
  user: "admin"
  password: "admin"
  post_server: false

ws:
  url: ""  # example: ws://main-server:9000/ws/agent
  token: ""
  auto_connect: false

webhook:
  mode: "listen"
  listen_path: "/api/update/receive-text"

polling:
  enabled: true
  url: ""  # example: http://vps-host:8005/api/polling
  lead: ""
  token: ""
  lan_uid: ""
  agent_uid: ""
  interval_seconds: 60
